version: '3.2'
services:
  strangerweb:
    #build:
    #  dockerfile: dockerfile-sweb.yml
    #  context: .
    image: drfresh613/strangerweb:0.0.1
    volumes:
      - /tmp/sweb_data:/opt/strangerweb/data
    ports:
      - "80:8000"
    restart: always
    deploy:
       labels:
         com.example.description: "Strangerlights web application"
       replicas: 3
       restart_policy:
         condition: on-failure
         delay: 5s
         max_attempts: 3

  slightstalkie:
    #build:
    #  dockerfile: dockerfile-slights.yml
    #  context: .
    image: drfresh613/slightstalkie:0.0.1
    environment:
      SWEB_HOST: strangerweb:8000
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    deploy:
       labels:
         com.example.description: "Stringerlights message handler"
       placement:
        constraints:
          - node.labels.type = arduino
       restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 5
    depends_on:
      - strangerweb
    restart: always